spring.application.name=Bank2
spring.datasource.url=jdbc:postgresql://localhost:5432/bank2
spring.datasource.username=postgres
spring.datasource.password=12345678

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL10Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8081